config/routes.rb
Rails.application.routes.draw do

  get 'accounts/my_account'

  get 'accounts/purchases'

  get 'purchases/create'

  get 'auctions/index'

  get 'auctions/show'

  get 'complements/index'

  get 'complements/show'

  get 'complements/new'

  get 'complements/create'

  get 'complements/edit'

  get 'complements/update'

  get 'complements/destroy'

  get 'repromaterijal/index'

  get 'repromaterijal/show'

  get 'trgovina/index'

  get 'trgovina/show'

  get 'past_purchases/index'

  get 'past_purchases/show'

  get 'past_purchases/create'

  get 'past_purchases/edit'

  get 'past_purchases/update'

  get 'past_purchases/destroy'

  get 'carts_articles/index'

  get 'carts_articles/show'

  get 'carts_articles/new'

  get 'carts_articles/create'

  get 'carts_articles/edit'

  get 'carts_articles/update'

  get 'carts_articles/destroy'

  get 'carts_articles/plus_no_user'

  get 'carts_articles/min_no_user'

  get 'shopping_carts/index'

  get 'shopping_carts/show'

  get 'shopping_carts/new'

  get 'shopping_carts/create'

  get 'shopping_carts/edit'

  get 'shopping_carts/update'

  get 'shopping_carts/destroy'

  get 'orders/index'

  get 'orders/show'

  get 'orders/new'

  get 'orders/create'

  get 'orders/edit'

  get 'orders/update'

  get 'orders/destroy'

  get 'shopping_carts/index'

  get 'shopping_carts/show'

  get 'clients/show'

  get 'articles/index'

  get 'articles/index_subcategories'

  get 'articles/show'

  get 'categories/index'

  get 'categories/show'

  get 'home/index'

  get 'trgovina/categories' => "trgovina#categories", :as => 'categories'

  get 'trgovina/index_of' => "trgovina#index_of", :as => 'index_of'

  get 'repromaterijal/categories' => "repromaterijal#categories", :as => 'categories_repro'

  get 'repromaterijal/index_of' => "repromaterijal#index_of", :as => 'index_of_repro'

  get 'articles/search_art' => "articles#search_art", :as => 'search_art'

  get 'auctions/complement_show' => "auctions#complement_show", :as => 'complement_show'

  get 'home/general' => "home#general", :as => 'general'

  get 'home/download_pdf' => "home#download_pdf", :as => 'download_pdf'

  get 'home/privacy'

  resources :home do
    get :general, on: :collection
    get :download_pdf, on: :collection
  end
  resources :purchases
  resources :auctions do
    put :new_bid, on: :collection
    put :complement_show, on: :collection
  end
  resources :articles do
    put :search_art, on: :collection
  end
  resources :complements
  resources :categories
  resources :clients
  resources :subcategories
  resources :ssubcategories
  resources :shopping_carts do
    put :destroy_single, on: :collection
    put :destroy_complement, on: :collection
  end
  resources :carts_articles do
    put :single, on: :collection
    post :create_single, on: :collection
    put :plus_no_user, on: :collection
    put :min_no_user, on: :collection
    put :create_complement, on: :collection

  end
  resources :trgovina do
    get :categories, on: :collection
    put :index_of, on: :collection
  end
  resources :repromaterijal do
    get :categories, on: :collection
    put :index_of, on: :collection
  end

  devise_for :users, controllers: { registrations: "users/registrations"}

   root 'home#index'

end

app/models/shopping_cart.rb
class ShoppingCart < ActiveRecord::Base
  belongs_to :user

  has_many :carts_articles
  has_many :single_articles, :through => :carts_articles

  has_many :carts_articles
  has_many :articles, :through => :carts_articles

  has_many :carts_articles
  has_many :complements, :through => :carts_articles

end

app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < ApplicationController
 # before_action :authenticate_user!
  before_filter :set_user, :set_cart
  def index


  end

  def show
    if current_user == nil
      #$no_user_articles.each do |k, v|
        @no_articles = Article.where(id: $no_user_articles.keys)

        @sa = SingleArticle.where(id: $no_user_single_articles.keys)

      $no_user_single_articles.each do |k,v|
        puts "#{k}"
      end

    else
      @shopping_cart = ShoppingCart.find_by(user_id: current_user.id)
      @carts_article = CartsArticle.find_by(shopping_cart_id: @shopping_cart.id )
    end

  end

  def new

  end



  def create
    if current_user == nil

      @article = Article.find(params[:format])


      puts "Ispred if za provjeru jel se artikl nalazi u hash-u"
      if $no_user_articles.has_key?(@article.id.to_s)
        $no_user_articles.each do |k, v|
          if k == @article.id.to_s
            $no_user_articles[k] += 1
            $items_cost +=@article.cost
          end
        end
      else
        puts "Unutar if-else-a kada nije pronaden artikl unutar hash-a"
        $no_user_articles[params[:format]] = 1
        $items_cost +=@article.cost
      end



    else


      @shopping_cart = ShoppingCart.find_by(user_id: current_user.id)

      @carts_article = CartsArticle.find_by(shopping_cart_id: @shopping_cart.id, article_id: params[:format] )

      if @carts_article == nil
        CartsArticle.create(shopping_cart_id: @shopping_cart.id, article_id: params[:format], amount: 1 )
        @carts_article = CartsArticle.find_by(shopping_cart_id: @shopping_cart.id, article_id: params[:format] )
      else
        @carts_article.increment!(:amount)
      end



      @article = Article.find(params[:format])
      #@carts_articles = CartsArticle.all



      if @article.on_discount.nil? || @article.on_discount == false || @article.discount != 0
        if current_user == nil

          $items_cost += @article.cost

        else
          @shopping_cart.current_cost += @article.cost
          @shopping_cart.save
        end
      else
        if current_user == nil

          $items_cost += (@article.cost- (@article.cost*@article.discount/100))

        end
        @shopping_cart.current_cost += (@article.cost- (@article.cost*@article.discount/100))
        @shopping_cart.save
      end




    end



    redirect_to :back

  end

  def edit
  end

  def update

  end

  def destroy
    @article = Article.find(params[:format])

    puts "usao sam u destroy!!!!"

    if current_user == nil

      if $no_user_articles.has_key?(@article.id.to_s)

        $no_user_articles.each do |k, v|

          if k == @article.id.to_s && v.to_i > 1
            puts "ulazi u if"
            $no_user_articles[k] -= 1
            if @article.on_discount.nil? || @article.on_discount == false || @article.discount != 0
              $items_cost -= @article.cost

            else

              $items_cost -= (@article.cost- (@article.cost*@article.discount/100))

            end
          end

          if k == @article.id.to_s && v.to_i == 1
            puts "ulazi u else"
            if @article.on_discount.nil? || @article.on_discount == false || @article.discount != 0
              $items_cost -= @article.cost

            else
              $items_cost -= (@article.cost- (@article.cost*@article.discount/100))

            end
            $no_user_articles.delete(k)
          end

        end
      end

    else

    @shopping_cart = ShoppingCart.find_by(user_id: current_user.id)
    @carts_article = CartsArticle.find_by(shopping_cart_id: @shopping_cart.id, article_id: params[:format] )
    if @carts_article.amount > 1
      @carts_article.amount -= 1
      @carts_article.save

        @shopping_cart.current_cost -= @carts_article.cost
        @shopping_cart.save

    else

        @shopping_cart.current_cost -= @carts_article.cost
        @shopping_cart.save

      @carts_article.destroy!
    end
  end

    redirect_to :back
  end



  def destroy_single

    @single_article = SingleArticle.find(params[:format])
    @shopping_cart = ShoppingCart.find_by(user_id: current_user.id)
    @carts_article = CartsArticle.find_by(shopping_cart_id: @shopping_cart.id, single_article_id: params[:format] )

      puts "usao sam u destroy single"


    if @carts_article.amount > 1
      @carts_article.amount -= 1
      @carts_article.save

        @shopping_cart.current_cost -= @carts_article.cost
        @shopping_cart.save

    else

        @shopping_cart.current_cost -= @carts_article.cost
        @shopping_cart.save

      @carts_article.destroy!
    end



    redirect_to :back

  end


  def destroy_complement
    @single_article = Complement.find(params[:format])
    @shopping_cart = ShoppingCart.find_by(user_id: current_user.id)
    @carts_article = CartsArticle.find_by(shopping_cart_id: @shopping_cart.id, complement_id: params[:format] )

    puts "usao sam u destroy single"


    if @carts_article.amount > 1
      @carts_article.amount -= 1
      @carts_article.save
      if @single_article.on_discount.nil? || @single_article.on_discount == false || @single_article.discount != 0
        @shopping_cart.current_cost -= @single_article.cost
        @shopping_cart.save
      else
        @shopping_cart.current_cost -= (@single_article.cost- (@single_article.cost*@single_article.discount/100))
        @shopping_cart.save
      end
    else
      if @single_article.on_discount.nil? || @single_article.on_discount == false || @single_article.discount != 0
        @shopping_cart.current_cost -= @single_article.cost
        @shopping_cart.save
      else
        @shopping_cart.current_cost -= (@single_article.cost- (@single_article.cost*@single_article.discount/100))
        @shopping_cart.save
      end
      @carts_article.destroy!
    end



    redirect_to :back
  end












  private
  def cart_params
    params.require(:cart).permit(:id, :user_id, :current_cost)
  end


end

app/helpers/shopping_carts_helper.rb
module ShoppingCartsHelper
end

app/views/shopping_carts/create.html.erb
<h1>ShoppingCarts#create</h1>
<p>Find me in app/views/shopping_carts/create.html.erb</p>

app/views/shopping_carts/destroy.html.erb
<h1>ShoppingCarts#destroy</h1>
<p>Find me in app/views/shopping_carts/destroy.html.erb</p>

app/views/shopping_carts/edit.html.erb
<h1>ShoppingCarts#edit</h1>
<p>Find me in app/views/shopping_carts/edit.html.erb</p>

app/views/shopping_carts/index.html.erb
<% @shopping_cart.each do |id| %>

  <% article = Article.find.find_by_id(id) %>
  <%= link_to article.title, article_path %>

<% end %>

<%= link_to 'emty your cart', shopping_carts_clear_path %>

app/views/shopping_carts/new.html.erb
<h1>ShoppingCarts#new</h1>
<p>Find me in app/views/shopping_carts/new.html.erb</p>

app/views/shopping_carts/show.html.erb
<div class="panel panel-default" style="background-color: #1abc9c; margin: 25px 25px 25px 25px; ">

  <div class="panel-body" >
<ul class="list-group">

  <li class="list-group-item"  >
    <div class="row" >

      <div class="col-xs-6 col-md-1">

      </div>

      <div class="col-xs-6 col-md-3">
        <div class="item-title"> Naziv Artikla </div>
      </div>

      <div class="col-xs-6 col-md-4">
        <div class="col-xs-6 col-md-1" style="width: auto; height: auto;">

        </div>

        <div class="col-xs-6 col-md-2" style="width: auto; height:auto;">
          <div class="item-title"> Količina</div>
        </div>

        <div class="col-xs-6 col-md-2" style="width: auto; height: auto;">

        </div>
      </div>


      <div class="col-xs-6 col-md-2">
        <div class="item-title"  style="text-align: right;"> Pojedinačna Cijena </div>
      </div>

      <div class="col-xs-6 col-md-2" style="text-align: right;">
        <div class="item-title"> Cijena </div>
      </div>

    </div>
  </li>


  <% if current_user != nil %>

<% @shopping_cart.carts_articles.each do |a| %>



<!-- #TODO popusti -->
      <li class="list-group-item"  >
    <div class="row" >
      <% if !a.article.nil? %>
      <div class="col-xs-6 col-md-1" >
        <% if a.article.picture != nil %>
            <%= image_tag(a.article.picture.image.url(:table)) %>
        <% else %>
            <%=image_tag("default-placeholder.png", class: "productimg" ) %>
        <% end %>

      </div>

      <div class="col-xs-6 col-md-3" >
        <div class="item-title"> <%=  a.article.title  %> </div>
      </div>

      <div class="col-xs-6 col-md-4">
      <div class="col-xs-6 col-md-1" style="width: auto; height: auto;">
        <%= link_to '-', shopping_carts_destroy_path(a.article.id ), class: "btn btn-default" %>
      </div>

      <div class="col-xs-6 col-md-2" style="width: auto; height:auto;">
        <div class="item-title"> <%=  a.amount %></div>
      </div>

      <div class="col-xs-6 col-md-2" style="width: auto; height: auto;">
        <%= link_to '+', carts_articles_create_path(a.article.id ), class: "btn btn-default " %>
      </div>
      </div>


      <div class="col-xs-6 col-md-2">
        <div class="item-price" style="text-align: right;"><%=  number_to_currency(CartsArticle.find_by(shopping_cart_id: @shopping_cart.id, article_id: a.article.id ).cost, :unit => 'Kn', :format => "%n %u")  %></div>
      </div>

      <div class="col-xs-6 col-md-2" style="text-align: right;">
        <div class="item-price"><%=  number_to_currency(CartsArticle.find_by(shopping_cart_id: @shopping_cart.id, article_id: a.article.id ).cost*a.amount, :unit => 'Kn', :format => "%n %u")  %></div>
      </div>



    <% elsif !a.single_article.nil? %>



          <div class="col-xs-6 col-md-1" >
            <% if a.single_article.article.picture != nil %>
                <%= image_tag(a.single_article.article.picture.image.url(:table)) %>
            <% else %>
                <%=image_tag("default-placeholder-2.png", class: "productimg" ) %>
            <% end %>



          </div>

          <div class="col-xs-6 col-md-3" >
            <div class="item-title"> <%=  a.single_article.title  %> </div>
          </div>

          <div class="col-xs-6 col-md-4">
            <div class="col-xs-6 col-md-1" style="width: auto; height: auto;">
              <%= link_to '-', destroy_single_shopping_carts_path(a.single_article.id ), :method => :put, class: "btn btn-default" %>
            </div>

            <div class="col-xs-6 col-md-2" style="width: auto; height:auto;">
              <div class="item-title"> <%=  a.amount %></div>
            </div>

            <div class="col-xs-6 col-md-2" style="width: auto; height: auto;">

              <%= link_to '+', create_single_carts_articles_path(id: a.single_article.id), :method => :post, class: "btn btn-default " %>


            </div>
          </div>


          <div class="col-xs-6 col-md-2">
            <div class="item-price" style="text-align: right;"><%=  number_to_currency(CartsArticle.find_by(shopping_cart_id: @shopping_cart.id, single_article_id: a.single_article.id ).cost, :unit => 'Kn', :format => "%n %u")  %></div>
          </div>

          <div class="col-xs-6 col-md-2" style="text-align: right;">
            <div class="item-price"><%=  number_to_currency(CartsArticle.find_by(shopping_cart_id: @shopping_cart.id, single_article_id: a.single_article.id ).cost*a.amount, :unit => 'Kn', :format => "%n %u")  %></div>
          </div>

    <% else %>


          <div class="col-xs-6 col-md-1" >
            <% if a.complement.picture != nil %>
                <%= image_tag(a.complement.picture.image.url(:table)) %>
            <% else %>
                <%=image_tag("default-placeholder-2.png", class: "productimg" ) %>
            <% end %>



          </div>

          <div class="col-xs-6 col-md-3" >
            <div class="item-title"> <%=  a.complement.title  %> </div>
          </div>

          <div class="col-xs-6 col-md-4">
            <div class="col-xs-6 col-md-1" style="width: auto; height: auto;">
              <%= link_to '-', destroy_complement_shopping_carts_path(a.complement.id ), :method => :put, class: "btn btn-default" %>
            </div>

            <div class="col-xs-6 col-md-2" style="width: auto; height:auto;">
              <div class="item-title"> <%=  a.amount %></div>
            </div>

            <div class="col-xs-6 col-md-2" style="width: auto; height: auto;">

              <%= link_to '+', create_complement_carts_articles_path(a.complement.id ), :method => :put, class: "btn btn-default " %>


            </div>
          </div>


          <div class="col-xs-6 col-md-2">
            <div class="item-price" style="text-align: right;"><%if !a.complement.on_discount.nil? && !a.complement.on_discount? && a.complement.discount != 0 %> <%=  number_to_currency((a.complement.cost-(a.complement.cost*a.complement.discount/100)), :unit => 'Kn', :format => "%n %u")  %> <% else %> <%=  number_to_currency(a.complement.cost, :unit => 'Kn', :format => "%n %u")  %> <% end %></div>
          </div>

          <div class="col-xs-6 col-md-2" style="text-align: right;">
            <div class="item-price"><%if !a.complement.on_discount.nil? && !a.complement.on_discount? && a.complement.discount != 0 %> <%=  number_to_currency((a.complement.cost-(a.complement.cost*a.single_article.article.discount/100))*a.amount, :unit => 'Kn', :format => "%n %u")  %> <% else %> <%=  number_to_currency(a.complement.cost*a.amount, :unit => 'Kn', :format => "%n %u")  %> <% end %></div>
          </div>


    <% end %>
    </div>
      </li>
    <% end %>
  <li class="list-group-item"  >
    <div class="row" >
      <div class="col-xs-6 col-md-12">
    <div class="item-title" style="text-align: right;">Ukupna cijena izabranih proizvoda je:</div>

    <% if current_user != nil %>
        <div style="text-align: right"><p>Bez PDV-a: <%= number_to_currency(@cijena_bez_pdv = (@shopping_cart.current_cost-(@shopping_cart.current_cost*0.2)), :unit => 'Kn', :format => "%n %u") %></p></div>
        <div style="text-align: right"><p>PDV: <%= number_to_currency(@shopping_cart.current_cost - @cijena_bez_pdv, :unit => 'Kn', :format => "%n %u") %> </p></div>

        <div class="item-price"  style="text-align: right; font-size: 200%;"><hr><%= number_to_currency(@shopping_cart.current_cost, :unit => 'Kn', :format => "%n %u") %></div>
        </br>
    <% end %>
        </div>
    </div>
  </li>



      <% else %>

        <% $no_user_articles.each do |k, v| %>
          <% @no_articles.each do |a| %>

              <% if a.id == k.to_i %>
              <li class="list-group-item"  >
                <div class="row" >

                  <div class="col-xs-6 col-md-1" >
                  <% if a.picture != nil %>
                      <%= image_tag(a.picture.image.url(:table)) %>
                  <% else %>
                      <%=image_tag("default-placeholder.png", class: "productimg" ) %>
                  <% end %>

                </div>

                <div class="col-xs-6 col-md-3" >
                  <div class="item-title"> <%=  a.title  %> </div>
                </div>

                <div class="col-xs-6 col-md-4">
                  <div class="col-xs-6 col-md-1" style="width: auto; height: auto;">
                    <%= link_to '-', shopping_carts_destroy_path(a.id ), class: "btn btn-default" %>
                  </div>

                  <div class="col-xs-6 col-md-2" style="width: auto; height:auto;">
                    <div class="item-title"> <%=  "#{v}" %></div>
                  </div>

                  <div class="col-xs-6 col-md-2" style="width: auto; height: auto;">
                    <%= link_to '+', carts_articles_create_path(a.id ), class: "btn btn-default " %>
                  </div>
                </div>


                <div class="col-xs-6 col-md-2">
                  <div class="item-price" style="text-align: right;"><%if !a.on_discount.nil? && !a.on_discount? && a.discount != 0 %> <%=  number_to_currency((a.cost-(a.cost*a.discount/100)), :unit => 'Kn', :format => "%n %u")  %> <% else %> <%=  number_to_currency(a.cost, :unit => 'Kn', :format => "%n %u")  %> <% end %></div>
                </div>

                <div class="col-xs-6 col-md-2" style="text-align: right;">
                  <div class="item-price"><%if !a.on_discount.nil? && !a.on_discount? && a.discount != 0 %> <%=  number_to_currency((a.cost-(a.cost*a.discount/100))*v, :unit => 'Kn', :format => "%n %u")  %> <% else %> <%=  number_to_currency(a.cost*v, :unit => 'Kn', :format => "%n %u")  %> <% end %></div>
                </div>



              <% end %>
          <% end %>

          </div>
          </li>
         <% end %>

      <% $no_user_single_articles.each do |k, v| %>
          <% @sa.each do |a| %>
              <% if a.id == k %>
                  <li class="list-group-item"  >
                    <div class="row" >

                      <div class="col-xs-6 col-md-1" >
                        <% if a.pictures.first != nil %>
                            <%= image_tag(a.pictures.first.image.url(:table)) %>
                        <% else %>
                            <%=image_tag("default-placeholder.png", class: "productimg" ) %>
                        <% end %>

                      </div>

                      <div class="col-xs-6 col-md-3" >
                        <div class="item-title"> <%=  a.title  %> </div>
                      </div>

                      <div class="col-xs-6 col-md-4">
                        <div class="col-xs-6 col-md-1" style="width: auto; height: auto;">
                          <%= link_to '-', min_no_user_carts_articles_path(a.id ), :method => :put ,class: "btn btn-default" %>
                        </div>

                        <div class="col-xs-6 col-md-2" style="width: auto; height:auto;">
                          <div class="item-title"> <%=  "#{v}" %></div>
                        </div>

                        <div class="col-xs-6 col-md-2" style="width: auto; height: auto;">
                          <%= link_to '+', plus_no_user_carts_articles_path(a.id ), :method => :put, class: "btn btn-default " %>
                        </div>
                      </div>


                      <div class="col-xs-6 col-md-2">
                        <div class="item-price" style="text-align: right;"><%if !a.article.on_discount.nil? && !a.article.on_discount? && a.article.discount != 0 %> <%=  number_to_currency((a.article.cost-(a.article.cost*a.article.discount/100)), :unit => 'Kn', :format => "%n %u")  %> <% else %> <%=  number_to_currency(a.article.cost, :unit => 'Kn', :format => "%n %u")  %> <% end %></div>
                      </div>

                      <div class="col-xs-6 col-md-2" style="text-align: right;">
                        <div class="item-price"><%if !a.article.on_discount.nil? && !a.article.on_discount? && a.article.discount != 0 %> <%=  number_to_currency((a.article.cost-(a.article.cost*a.article.discount/100))*v, :unit => 'Kn', :format => "%n %u")  %> <% else %> <%=  number_to_currency(a.article.cost*v, :unit => 'Kn', :format => "%n %u")  %> <% end %></div>
                      </div>



              <% end %>
          <% end %>

          </div>
          </li>
      <% end %>










      <li class="list-group-item"  >
        <div class="row" >
          <div class="col-xs-6 col-md-12">
            <div class="item-title" style="text-align: right;">Ukupna cijena izabranih proizvoda je:</div>

            <div class="item-price"  style="text-align: right;"><%= number_to_currency($items_cost, :unit => 'Kn', :format => "%n %u") %></div>
            </br>

          </div>
        </div>
      </li>



      <% end %>

</ul>


<div style="margin-top: 20px;">
<%= link_to 'Kupi', purchases_create_path, class: "btn btn-default pull-right btn-lg" , style:"margin-right: 15px;" %>
</div>

</div>
</div>

app/views/shopping_carts/update.html.erb
<h1>ShoppingCarts#update</h1>
<p>Find me in app/views/shopping_carts/update.html.erb</p>