config/routes.rb
Rails.application.routes.draw do

  get 'accounts/my_account'

  get 'accounts/purchases'

  get 'purchases/create'

  get 'auctions/index'

  get 'auctions/show'

  get 'complements/index'

  get 'complements/show'

  get 'complements/new'

  get 'complements/create'

  get 'complements/edit'

  get 'complements/update'

  get 'complements/destroy'

  get 'repromaterijal/index'

  get 'repromaterijal/show'

  get 'trgovina/index'

  get 'trgovina/show'

  get 'past_purchases/index'

  get 'past_purchases/show'

  get 'past_purchases/create'

  get 'past_purchases/edit'

  get 'past_purchases/update'

  get 'past_purchases/destroy'

  get 'carts_articles/index'

  get 'carts_articles/show'

  get 'carts_articles/new'

  get 'carts_articles/create'

  get 'carts_articles/edit'

  get 'carts_articles/update'

  get 'carts_articles/destroy'

  get 'carts_articles/plus_no_user'

  get 'carts_articles/min_no_user'

  get 'shopping_carts/index'

  get 'shopping_carts/show'

  get 'shopping_carts/new'

  get 'shopping_carts/create'

  get 'shopping_carts/edit'

  get 'shopping_carts/update'

  get 'shopping_carts/destroy'

  get 'orders/index'

  get 'orders/show'

  get 'orders/new'

  get 'orders/create'

  get 'orders/edit'

  get 'orders/update'

  get 'orders/destroy'

  get 'shopping_carts/index'

  get 'shopping_carts/show'

  get 'clients/show'

  get 'articles/index'

  get 'articles/index_subcategories'

  get 'articles/show'

  get 'categories/index'

  get 'categories/show'

  get 'home/index'

  get 'trgovina/categories' => "trgovina#categories", :as => 'categories'

  get 'trgovina/index_of' => "trgovina#index_of", :as => 'index_of'

  get 'repromaterijal/categories' => "repromaterijal#categories", :as => 'categories_repro'

  get 'repromaterijal/index_of' => "repromaterijal#index_of", :as => 'index_of_repro'

  get 'articles/search_art' => "articles#search_art", :as => 'search_art'

  get 'auctions/complement_show' => "auctions#complement_show", :as => 'complement_show'

  get 'home/general' => "home#general", :as => 'general'

  get 'home/download_pdf' => "home#download_pdf", :as => 'download_pdf'

  get 'home/privacy'

  resources :home do
    get :general, on: :collection
    get :download_pdf, on: :collection
  end
  resources :purchases
  resources :auctions do
    put :new_bid, on: :collection
    put :complement_show, on: :collection
  end
  resources :articles do
    put :search_art, on: :collection
  end
  resources :complements
  resources :categories
  resources :clients
  resources :subcategories
  resources :ssubcategories
  resources :shopping_carts do
    put :destroy_single, on: :collection
    put :destroy_complement, on: :collection
  end
  resources :carts_articles do
    put :single, on: :collection
    post :create_single, on: :collection
    put :plus_no_user, on: :collection
    put :min_no_user, on: :collection
    put :create_complement, on: :collection

  end
  resources :trgovina do
    get :categories, on: :collection
    put :index_of, on: :collection
  end
  resources :repromaterijal do
    get :categories, on: :collection
    put :index_of, on: :collection
  end

  devise_for :users, controllers: { registrations: "users/registrations"}

   root 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :set_user, :set_cart

  def index
    add_breadcrumb "Home", :root_path

    if user_signed_in?
       @cart = ShoppingCart.where(user_id: current_user.id)

      if @cart.empty?
        ShoppingCart.create(user_id: current_user.id)
       end
    end

    if params[:format] != nil
    @article = Article.find(params[:format])
    end

    @categories = Category.all
    @articles = Article.where(raw: false, for_sale: true).order('created_at DESC')

    if current_user != nil
    @shopping_cart = ShoppingCart.find_by(user_id: current_user.id)
    @carts_article = CartsArticle.find_by(shopping_cart_id: @shopping_cart.id )
    else
      @no_articles = Article.where(id: $no_user_articles.keys)
      @sa = SingleArticle.where(id: $no_user_single_articles.keys)
    end

  end

  def general
    if user_signed_in?
      @cart = ShoppingCart.where(user_id: current_user.id)

      if @cart.empty?
        ShoppingCart.create(user_id: current_user.id)
      end
    end

  end

  def download_pdf
    send_file(
        "#{Rails.root}/public/assets/Obrazac-za-jednostrani-raskid-ugovora_1.pdf",
        filename: "Obrazac za jednostrani raskid ugovora.pdf",
        type: "application/pdf"
    )
  end


end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/general.erb
<div class="prdt" style="padding-top: 10px">
  <div class="container">
<div class="page-header head-page">
  <h1>Opći uvjeti korištenja web stranica i korištenja usluge web trgovine</h1>
</div>

<div class="page-header head-page">
  <h2>
    OPĆE ODREDBE I DEFINICIJE
  </h2>
</div>

  <p>
    Ovim se Općim uvjetima uređuje korištenje web stranica od strane korisnika, te korištenje Webtrgovine. Korisnike upućujemo da se prije kupnje upoznaju sa ovim Uvjetima te da iste redovito provjeravaju, kako bi bili upoznati sa svim vašim pravima i obvezama.
  </p>
  <p>
    U Općim uvjetima pojmovi pisani podebljanim slovima imat će značenje dano u nastavku:
  </p>
  <p>
    <strong>Web stranice</strong> označava sve web, odnosno Internet stranice u vlasništvu Argentum Vita d.o.o., uključujući, ali se ne ograničavajući na www.ArgentumVita.hr.
  </p>
  <p>
    <strong>Korisnik</strong> znači svaku osobu, pravnu ili fizičku, koja pristupa web stranicama. Pojam korisnik uključuje i registriranog korisnika.
  </p>
  <p>
    <strong>Registrirani korisnik</strong> znači svaku potpuno poslovno sposobnu osobu, pravnu ili fizičku, koja se registrirala za korištenje usluge webtrgovine na web stranicama.
  </p>
  <p>
    <strong>Argentum Vita</strong> znači Argentum Vita d.o.o., sa sjedištem u Zagrebu, Vrapčanska 175/2, upisano u sudski registar Trgovačkog suda u Zagrebu pod matičnim brojem subjekta upisa (MBS) , OIB 70900900444
  </p>
  <p>
    Pristupom web stranicama putem odgovarajućeg tehničkog sredstva pristupa i njihovim korištenjem svaki korisnik se obvezuje poštivati ove Opće uvjete i pristaje da se na njega primjenjuju odredbe ovih Općih uvjeta.
  </p>
<div class="page-header head-page">
  <h2>
    OGRANIČENJA KORIŠTENJA I ODGOVORNOSTI
  </h2>
</div>
  <p>
    Korisnik se obvezuje da neće:
  </p>
  <p>
    - koristiti web stranice na bilo koji način koji je protivan pozitivnim propisima;<br />
    - unositi na web stranice ili distribuirati putem web stranica bilo kakve sadržaje koji su u protivni pozitivnim propisima, uključujući, ali se ne ograničavajući na štetne, prijeteće, uznemiravajuće, vulgarne, pornografske sadržaje, sadržaje koji šire mržnju i rasnu netrpeljivost, sadržaje koji povređuju tuđa prava i interese i slično;<br />
    - mijenjati, brisati ili uništavati bilo kakve podatke na web stranicama;<br />
    - koristiti web stranice za kršenje prava trećih osoba, uključujući za povredu tajne, prava intelektualnog vlasništva ili drugog prava ili interesa trećih osoba;<br />
    - koristiti web stranice za slanje elektroničke pošte protivne ovim Općim uvjetima;<br />
    - unositi ili distribuirati putem web stranica bilo kakav nelegalan software, uključujući ali se ne ograničavajući na viruse, spyware, trojane, ili slično.
  </p>
  <p>
    Dokumenti, podaci i informacije objavljeni na web stranicama ne smiju se reproducirati, distribuirati ili na bilo koji način koristiti u komercijalne svrhe bez izričitog pristanka Argentum Vita ili na bilo koji način koji može uzrokovati štetu Argentum Vita ili bilo kojoj trećoj strani. Dokumenti, podaci i informacije objavljeni na ovoj web stranicama mogu se koristiti samo za individualne potrebe korisnika uz poštivanje svih autorskih i vlasničkih prava te prava trećih osoba.
  </p>
  <p>
    Korištenjem sadržaja ovih web stranica korisnik prihvaća sve rizike koji nastaju iz korištenja web stranica te prihvaća i koristiti sadržaj web stranica isključivo za osobnu uporabu i na vlastitu odgovornost.
  </p>
  <p>
    Argentum Vita se u potpunosti odriče svake odgovornosti koja na bilo koji način može nastati iz, ili je na bilo koji način vezana za korištenje web stranica, i za bilo koje radnje korisnika uporabom ili zlouporabom sadržaja web stranica, te za bilo kakvu štetu koja može nastati korisniku ili bilo kojoj trećoj strani u vezi s uporabom ili zlouporabom korištenja sadržaja web stranica.
  </p>
  <p>
    Web stranice sadrže i dokumente, podatke, informacije kao i veze ("linkove") do drugih Internet stranica kreiranih od strane trećih osoba koje će se, u opsegu u kojem je to potrebno i moguće, kao takve označavati. Argentum Vita nema nadzor nad navedenim dokumentima, podacima, informacijama ili drugim Internet stranicama uopće te se u potpunosti odriče svake odgovornosti, uključujući ali ne ograničeno na točnost, potpunost i dostupnost sadržaju na Internet stranicama kreiranim od strane trećih
    osoba. Argentum Vita se odriče svake odgovornosti zbog bilo kojeg sadržaja prikazanog na takvim stranicama trećih osoba, kao i zbog eventualnih proizvoda ili usluga koji su se stekli putem takvih trećih stranica. Neće se smatrati da su takve treće osobe na bilo koji način povezane s Argentum Vita samo zbog postojanja veze s web stranicom.
  </p>
  <p>
    Argentum Vita zadržava pravo izmjene sadržaja web stranica, pravo ukidanja web stranica, te pravo ograničavanja pristupa web stranicama, sve bez najave te neće biti odgovoran ni za kakve moguće posljedice proizašle iz takvih promjena, ukidanja ili ograničavanja.
  </p>
  <p>
    Argentum Vita neće biti odgovoran ni za kakve moguće posljedice proizašle iz nedostupnosti web stranica zbog bilo kakvih tehničkih razloga.
  </p>
  <p>
    Argentum Vita zadržava pravo promjene cijena svojih proizvoda i usluga.
  </p>
  <p>
    Argentum Vita zadržava pravo da spriječi pristup web stranicama IP adresama, (odnosno korisnicima) s kojih se vrše radnje protivne ovim Općim uvjetima, te s te osnove neće snositi nikakvu odgovornost.
  </p>
<div class="page-header head-page">
  <h2>
    KORIŠTENJE USLUGE WEBTRGOVINE I REGISTRACIJA KORISNIKA
  </h2>
</div>
  <p>
    Korištenje usluge Webtrgovine je dostupno isključivo registriranim korisnicima koji su punoljetni i potpuno poslovno sposobni.
  </p>
  <p>
    Registracija korisnika se vrši putem web stranica, prilikom čega će korisnik biti obvezan upisati određene osobne podatke i pristati na korištenje takvih osobnih podataka.
  </p>
  <p>
    Nakon uspješne registracije, registrirani korisnik dobiva na korištenje korisničko ime i lozinku koji služe za autorizaciju korištenja Webtrgovine
  </p>
  <p>
    Registracijom korisnik potvrđuje:
  </p>
  <p>
    - da u cijelosti prihvaća ove opće uvjete;<br />
    - potpunost, točnost, istinitost i ažurnost osobnih podataka;<br />
    - da daje Argentum Vita izričitu suglasnost da može sukladno odredbama Zakona o zaštiti osobnih podataka, obrađivati dane osobne podatke za potrebe vlastitih evidencija i pružanja drugih usluga, potrebe stvaranja baze podataka o kupcima, obavještavanja o novim proizvodima i uslugama.
  </p>
  <p>
    Registrirani korisnik pristaje da se kupnja putem Webtrgovine vrši na način da registrirani korisnik kupuje proizvode i usluge dostupne putem Webtrgovine ("proizvodi") na način da ih bira na temelju slike i osnovnog opisa proizvoda.
  </p>
  <p>
    Narudžba proizvoda se vrši elektronskim putem. Klikom na ikonu "dodaj u košaricu", odabrani proizvod sprema se u potrošačku košaricu. Za nastavak procedure potrebno je kliknuti "sadržaj košarice" gdje se nalaze svi odabrani artikli. Roba se smatra naručenom u trenutku kada kupac prođe cijeli proces narudžbe. Na e-mail adresu kojom ste se registrirali kao kupac, dobit ćete potvrdu da je narudžba zaprimljena od strane Argentum Vita.
  </p>
  <p>
    Ukoliko Argentum Vita nije u mogućnosti isporučiti neki od naručenih proizvoda, kontaktirat će kupca telefonski ili putem e-mail-a te ga obavijestiti o navedenom. Kupac ima pravo odustati od narudžbe takvog proizvoda ili zatražiti zamjenski proizvod.
  </p>
<div class="page-header head-page">
  <h2>
    CIJENE PROIZVODA I USLUGA PUTEM WEBTRGOVINE
  </h2>
</div>
  <p>
    Cijene proizvoda izražene su u hrvatskim kunama ("HRK") i uključuju porez na dodanu vrijednost (PDV).
  </p>
  <p>
    Cijene proizvoda su podložne promjenama do trenutka potvrde kupovine.
  </p>
  <p>
    Potvrdom kupovine registrirani korisnici završavaju postupak kupovine putem webtrgovine.
  </p>
  <p>
    Cijena dostave kupljenih proizvoda nije uključena u cijenu proizvoda.
  </p>
<div class="page-header head-page">
  <h2>
    SKLAPANJE I RASKID UGOVORA O PRODAJI
  </h2>
</div>
  <p>
    Ovi uvjeti kao i pojedini uvjeti naznačeni uz proizvode predstavljaju ponudu Argentum Vite za sklapanje Ugovora. Korisnik svojom registracijom, zaključivanjem narudžbe ili na drugi način utvrđen ovim uvjetima iste prihvaća čime se smatra da je zaključen Ugovor između korisnika i Argentum Vite.
  </p>
  <p>
    Predmet Ugovora je kupnja odabranog proizvoda ili usluge putem web trgovine www.argentumvita.hr
  </p>
  <p>
    Ugovor stupa na snagu od trenutka kada korisnik prihvati ponudu Argentum Vite na jedan od slijedećih načina:
  </p>
  <ul>
    <li>odabirom plaćanja i zaključivanjem narudžbe kao registrirani korisnik
    </li>
    <li>odabirom plaćanja i zaključivanjem narudžbe putem telefona
    </li>
    <li>odabiram plaćanja i slanjem narudžbe na mail: info@argentumvita.hr
    </li>
  </ul>
  <p>
    Sukladno zakonu o zaštiti potrošača korisnik Ugovor može jednostrano raskinuti u roku od 14 dana bez navođenja razloga.
  </p>
  <p>
    Da bi ostvario pravo na jednostrani raskid Ugovora, korisnik nas mora obavijestiti o svojoj odluci o jednostranom raskidu ugovora i to nedvosmislenom izjavom poslanom poštom ili elektroničkom poštom, u kojoj ćete navesti svoje ime i prezime, adresu, broj telefona, telefaksa ili adresu elektroničke pošte, a možete koristiti i priloženi primjer obrasca za jednostrani raskid ugovora
  </p>
  <p>
    <strong>Na dnu ove stranice nalazi se link za preuzimanje obrasca za jednostrani raskid ugovora</strong>
  </p>
  <p>
    Primjerak obrasca za jednostrani raskid ugovora koji se nalazi na našoj mrežnoj stranici možete elektronički ispuniti i poslati. Potvrdu primitka obavijesti o jednostranom raskidu ugovora dostavit ćemo Vam, bez odgađanja, elektroničkom poštom.
  </p>
  <p>
    Rok za jednostrani raskid iznosi 14 dana od dana kada je korisniku ili trećoj osobi koju je korisnik odredio, a koja nije prijevoznik, roba koja je predmet ugovora predana u posjed.
  </p>
  <p>
    Ako korisnik jednostrano raskine Ugovor, izvršit ćemo povrat novca koji smo od korisnika primili, uključujući i troškove isporuke, bez odgađanja, a najkasnije u roku od 14 dana od dana kada smo zaprimili korisnikovu odluku o jednostranom raskidu ugovora, osim ukoliko je korisnik odabrao drugu vrstu isporuke a koja nije najjeftinija standardna isporuka koju smo mi ponudili.
  </p>
  <p>
    Povrat novca bit će izvršen na isti način na koji ste Vi izvršili uplatu. U slučaju da pristajete na drugi način povrata plaćenog iznosa, ne snosite nikakve troškove u odnosu na povrat.
  </p>
  <p>
    Povrat novca možemo izvršiti tek nakon što nam roba bude vraćena ili nakon što nam korisnik dostavi dokaz da nam je robu poslao nazad.
  </p>
  <p>
    Korisnik robu treba poslati ili je predati nama bez nepotrebnog odgađanja, a u svakom slučaju najkasnije u roku od 14 dana od dana kada nam je uputio odluku o jednostranom raskidu ugovora.
  </p>
  <p>
    U slučaju korisnikovog jednostranog raskida ugovora izravne troškove povrata robe mora snositi korisnik.
  </p>
  <p>
    U slučaju korisnikovog jednostranog raskida ugovora korisnik je odgovoran za svako umanjenje vrijednosti robe koju vraća, koje je rezultat rukovanja robom, osim onog koje je bilo potrebno za utvrđivanje prirode, obilježja i funkcionalnosti robe.
  </p>
  <p>
    Za materijalne nedostatke odgovaramo sukladno odredbama Zakona o obveznim odnosima.
  </p>
  <p>
    Ukoliko je došlo do pogreške prilikom pakiranja naručenih proizvoda te korisnik nije dobio naručeni proizvod već neki drugi. U tom slučaju, korisnik vraća krivo isporučen proizvod na trošak Argentum Vita koji se obvezuje isporučiti naručeni proizvod ili izvršiti povrat novca (sukladno zahtjevu korisnika) u roku od 14 dana od zaprimljenog krivo isporučenog artikla.
  </p>
  <p>
    <strong>PRIGOVORI I REKLAMACIJE KUPACA</strong>
  </p>
  <p>
    Reklamacije i prigovori mogu se izjaviti u pisanoj formi putem elektroničke ili obične pošte:
  </p>
  <ul>
    <li>na e-mail adresu: info@argentumvita.hr
    </li>
    <li>na adresu: Argentum Vita d.o.o., Vrapčanska 175/2, 10090 Zagreb
    </li>
  </ul>
  <p>
    Odredbom Europske unije od 15.02.2016. u pogon je stavljena platforma za online rješavanje potrošačkih sporova -ORS platforma. Platformi možete pristupiti preko slijedeće elektronske poveznice (linka) <strong><a href="https://webgate.ec.europa.eu/odr/main/index.cfm?event=main.home.chooseLanguage" target="_blank" style="color: blue">https://webgate.ec.europa.eu/odr/main/index.cfm?event=main.home.chooseLanguage</a></strong>
  </p>

  <div class="page-header head-page">
    <h2>
      IZMJENE OPĆIH UVJETA I OSTALE ODREDBE
    </h2>
  </div>
  <p>
    ArgentumVita zadržava pravo izmijeniti ove Opće uvjete bez prethodne najave. Registrirani korisnici su dužni prilikom svakog korištenja web stranica, provjeriti važeće Opće uvjete. Važeći opći uvjeti bit će objavljeni na web stranicama.

  <h3>Datoteke za download</h3>
<%= link_to 'OBRAZAC za jednostrani raskid ugovora', download_pdf_path, style:"color: blue" %>
  </div>
</div>

app/views/home/index.html.erb
<!--bottom-header-->

<!--banner-starts-->
<div class="bnr" id="home">
  <div id="top" class="callbacks_container">
    <ul class="rslides" id="slider4">
      <% HomeBanner.where(active: true).each do |bann| %>
        <li>
          <%=image_tag(bann.image.url(:bann)) %>
        </li>
      <% end %>
    </ul>
  </div>
        <div class="clearfix"> </div>
</div>
<!--banner-ends-->

<!--about-starts-->

<div class="about">
  <div class="container">
    <div class="about-top grid-1">
      <div class="col-md-4 about-left">
        <%= link_to trgovina_index_path do %>
        <figure class="effect-bubba shadow">
          <%=image_tag("slika_kateg.jpg", class: "img-responsive" ) %>
          <!--TODO: upisati naziv kategorije-->
          <figcaption>
            <h2>Gotov Nakit</h2>
            <p>Srebrni, Čelični, Modni...</p>
          </figcaption>
        </figure>
        <% end %>
      </div>
      <div class="col-md-4 about-left">
        <%= link_to repromaterijal_index_path do %>
        <figure class="effect-bubba shadow">
          <%=image_tag("slika_kateg.jpg", class: "img-responsive" ) %>
          <!--TODO: upisati naziv kategorije-->
          <figcaption>
            <h2>Repromaterijal</h2>
            <p>Materijal za izradu nakita...</p>
          </figcaption>
        </figure>
        <% end %>
      </div>
      <div class="col-md-4 about-left">
        <%= link_to auctions_index_path do %>
        <figure class="effect-bubba shadow">
          <%=image_tag("slika_kateg.jpg", class: "img-responsive" ) %>
          <!--TODO: upisati naziv kategorije-->
          <figcaption>
            <h2>Aukcije</h2>
            <p>Nakit na aukciji...</p>
          </figcaption>
        </figure>
        <% end %>
      </div>

      <div class="clearfix"></div>
    </div>
  </div>
</div>

<!--about-end-->

<!--product-starts-->
<div class="product">
  <div class="container">
    <div class="product-top">




      <% i=0 %>
          <% @articles.each do |art| %>
          <%if i == 8 then %>
              <% break %>
          <% end %>
          <% i+=1 %>



            <div class="product-one col-md-3 product-left ">
              <% if art.on_discount == true && art.end_date != nil %>
                  <div class="timer_popust" >
                    <h5><div data-countdown="<%= art.end_date.strftime("%Y/%m/%d %H:%M") %>" style="color: white;"></div></h5>
                  </div>
              <% end %>
              <div class="product-main simpleCart_shelfItem">
                <!--TODO: upisati naziv slike-->
                <%=link_to  trgovina_show_path(art.id)  do %> <%= image_tag(art.picture.image.url(:index), class: "img-responsive zoom-img") %> <% end %>
                <!--<a href="#dialog" name="modal" class="mask"> </a>-->
                <div class="product-bottom">
                  <h3> <%= art.title %> </h3>
                  <!--NOTE: kratki opis od jednog reda-->

                  <% if art.short_description != nil && art.short_description !="" %>
                      <h4><%= art.short_description  %></h4>
                  <% else %>
                      <h4>-</h4>
                  <% end %>

                  <% if art.on_discount == true && art.discount != 0 %>
                      <h4><%= link_to carts_articles_create_path(art.id ), class: "item_add"  do %><i></i><% end %><span class=" item_price"><%= number_to_currency(art.cost-(art.cost*art.discount/100), :unit => 'Kn', :format => "%n %u") %></span></h4>
                  <% else %>
                      <h4><%= link_to carts_articles_create_path(art.id ), class: "item_add"  do %><i></i><% end %><span class=" item_price"><%= number_to_currency(art.cost, :unit => 'Kn', :format => "%n %u") %></span></h4>
                  <% end %></div>
                <% if art.on_discount == true && art.discount != 0 %>
                    <div class="srch">
                      <span><%= art.discount %>%</span>
                    </div>
                <% end %>
              </div>
            </div>

        <% end %>

    </div>
  </div>
</div>

<!--product-end-->









<!--Registration Form dialog-->



<!--Registration Form dialog end -->


<script>

  $('[data-countdown]').each(function() {
    var $this = $(this), finalDate = $(this).data('countdown');
    $this.countdown(finalDate, function(event) {
      $this.html(event.strftime('%D dana %H:%M:%S'));
    });
  })
</script>

app/views/home/privacy.erb
<div class="prdt" style="padding-top: 10px">
  <div class="container">
    <div class="page-header head-page">
      <h1>Izjava o privatnosti i sigurnosti podataka</h1>
    </div>
  <p>
    Tvrtka Argentum Vita će poštivati anonimnost i privatnost korisnika ove web stranice. Tvrtka Argentum Vita može prikupljati osobne podatke korisnika, kao što su ime, adresa, telefonski broj ili e-mail adresa samo ako korisnik iste dobrovoljno dostavi tvrtci Argentum Vita.
  </p>
  <p>
    Argentum Vita se obvezuje da će sve Vaše osobne podatke koristiti isključivo u svrhu kreiranja računa, kontakta s Vama, dostave kupljene robe i za ostale slične namjene.
  </p>
  <p>
    Argentum Vita obvezuje se da neće prodati, iznajmiti ili dijeliti Vaše podatke trećoj strani bez Vaše suglasnosti.
  </p>
  </div>
</div>