config/routes.rb
Rails.application.routes.draw do

  get 'accounts/my_account'

  get 'accounts/purchases'

  get 'purchases/create'

  get 'auctions/index'

  get 'auctions/show'

  get 'complements/index'

  get 'complements/show'

  get 'complements/new'

  get 'complements/create'

  get 'complements/edit'

  get 'complements/update'

  get 'complements/destroy'

  get 'repromaterijal/index'

  get 'repromaterijal/show'

  get 'trgovina/index'

  get 'trgovina/show'

  get 'past_purchases/index'

  get 'past_purchases/show'

  get 'past_purchases/create'

  get 'past_purchases/edit'

  get 'past_purchases/update'

  get 'past_purchases/destroy'

  get 'carts_articles/index'

  get 'carts_articles/show'

  get 'carts_articles/new'

  get 'carts_articles/create'

  get 'carts_articles/edit'

  get 'carts_articles/update'

  get 'carts_articles/destroy'

  get 'carts_articles/plus_no_user'

  get 'carts_articles/min_no_user'

  get 'shopping_carts/index'

  get 'shopping_carts/show'

  get 'shopping_carts/new'

  get 'shopping_carts/create'

  get 'shopping_carts/edit'

  get 'shopping_carts/update'

  get 'shopping_carts/destroy'

  get 'orders/index'

  get 'orders/show'

  get 'orders/new'

  get 'orders/create'

  get 'orders/edit'

  get 'orders/update'

  get 'orders/destroy'

  get 'shopping_carts/index'

  get 'shopping_carts/show'

  get 'clients/show'

  get 'articles/index'

  get 'articles/index_subcategories'

  get 'articles/show'

  get 'categories/index'

  get 'categories/show'

  get 'home/index'

  get 'trgovina/categories' => "trgovina#categories", :as => 'categories'

  get 'trgovina/index_of' => "trgovina#index_of", :as => 'index_of'

  get 'repromaterijal/categories' => "repromaterijal#categories", :as => 'categories_repro'

  get 'repromaterijal/index_of' => "repromaterijal#index_of", :as => 'index_of_repro'

  get 'articles/search_art' => "articles#search_art", :as => 'search_art'

  get 'auctions/complement_show' => "auctions#complement_show", :as => 'complement_show'

  get 'home/general' => "home#general", :as => 'general'

  get 'home/download_pdf' => "home#download_pdf", :as => 'download_pdf'

  get 'home/privacy'

  resources :home do
    get :general, on: :collection
    get :download_pdf, on: :collection
  end
  resources :purchases
  resources :auctions do
    put :new_bid, on: :collection
    put :complement_show, on: :collection
  end
  resources :articles do
    put :search_art, on: :collection
  end
  resources :complements
  resources :categories
  resources :clients
  resources :subcategories
  resources :ssubcategories
  resources :shopping_carts do
    put :destroy_single, on: :collection
    put :destroy_complement, on: :collection
  end
  resources :carts_articles do
    put :single, on: :collection
    post :create_single, on: :collection
    put :plus_no_user, on: :collection
    put :min_no_user, on: :collection
    put :create_complement, on: :collection

  end
  resources :trgovina do
    get :categories, on: :collection
    put :index_of, on: :collection
  end
  resources :repromaterijal do
    get :categories, on: :collection
    put :index_of, on: :collection
  end

  devise_for :users, controllers: { registrations: "users/registrations"}

   root 'home#index'

end

app/controllers/repromaterijal_controller.rb
class RepromaterijalController < ApplicationController
  before_filter :set_user, :set_cart

  add_breadcrumb "Home", :root_path
  add_breadcrumb "Repromaterijal", :repromaterijal_index_path

  def categories
    if current_user == nil
    @no_articles = Article.where(id: $no_user_articles.keys)
    @sa = SingleArticle.where(id: $no_user_single_articles.keys)

    else
    @shopping_cart = ShoppingCart.find_by(user_id: current_user.id)
    @carts_article = CartsArticle.find_by(shopping_cart_id: @shopping_cart.id )

    end

    ########################################################## dodan za search ###########################################################
    @page_title = "Artikli"
    @filterrific = initialize_filterrific(Subcategory.all, params[:filterrific]) or return
    @subcategories = @filterrific.find.page(params[:page])

    respond_to do |format|
      format.html
      format.js
    end

  rescue ActiveRecord::RecordNotFound => e
    # There is an issue with the persisted param_set. Reset it.
    puts "Had to reset filterrific params: #{ e.message }"
    redirect_to(reset_filterrific_url(format: :html)) and return
    ############################################################################################################################################


  end


  def index_of


    @ssubcategories = Ssubcategory.where(id: SsubcategorySubcategory.where(subcategory_id: params[:id]).pluck(:ssubcategory_id) )
    @subcategories = Subcategory.all

    puts "Usao je u trgovina#index"

    if current_user != nil
      @shopping_cart = ShoppingCart.find_by(user_id: current_user.id)

      puts "Shopping cart ID: #{@shopping_cart.id}"

      @carts_article = CartsArticle.find_by(shopping_cart_id: @shopping_cart.id )
    else
      puts "NEMA USER-A!!!!"

      @no_articles = Article.where(id: $no_user_articles.keys)
      @sa = SingleArticle.where(id: $no_user_single_articles.keys)
    end

    if params[:id] != nil
      $subcategory_id = params[:id]
    end

    gon.max = Article.where(raw: true, for_sale: true, subcategory_id: $subcategory_id ).order(cost: :desc).pluck(:cost).first.to_f.ceil

    puts "Najveca cijena je #{gon.max}"

    gon.min = Article.where(raw: true, for_sale: true, subcategory_id: $subcategory_id ).order(:cost).pluck(:cost).first.to_f.ceil

    puts "Najmanja cijena je #{gon.min}"

    # filterific ###########################################################################################################################
    @page_title = "Artikli"
    @filterrific = initialize_filterrific(Article.where(raw: true, for_sale: true, subcategory_id: $subcategory_id ), params[:filterrific], select_options: { sorted_by: Article.options_for_sorted_by,
                                                                                                                                                              with_subcategory_id: Subcategory.options_for_select,
                                                                                                                                                              with_ssubcategory_id: Ssubcategory.options_for_select,
                                                                                                                                                              with_color_id: Color.options_for_select,
                                                                                                                                                              with_type_id: Type.options_for_select}) or return


    @articles = @filterrific.find.page(params[:page])

    respond_to do |format|
      format.html
      format.js
    end


  rescue ActiveRecord::RecordNotFound => e
    # There is an issue with the persisted param_set. Reset it.
    puts "Had to reset filterrific params: #{ e.message }"
    redirect_to(reset_filterrific_url(format: :html)) and return

    ###########################################################################################################################

  end

  def index
    add_breadcrumb "Repromaterijal", :repromaterijal_index_path

    @ssubcategories = Ssubcategory.all
    @subcategories = Subcategory.all

    puts "Usao je u trgovina#index"

    if current_user != nil
      @shopping_cart = ShoppingCart.find_by(user_id: current_user.id)

      puts "Shopping cart ID: #{@shopping_cart.id}"

      @carts_article = CartsArticle.find_by(shopping_cart_id: @shopping_cart.id )
    else
      puts "NEMA USER-A!!!!"

      @no_articles = Article.where(id: $no_user_articles.keys)
      @sa = SingleArticle.where(id: $no_user_single_articles.keys)
    end

    if params[:id] != nil
      $subcategory_id = params[:id]
    end

    gon.max = Article.where(raw: true, for_sale: true ).order(cost: :desc).pluck(:cost).first.to_f.ceil

    puts "Najveca cijena je #{gon.max}"

    gon.min = Article.where(raw: true, for_sale: true ).order(:cost).pluck(:cost).first.to_i

    puts "Najmanja cijena je #{gon.min}"
    $ssub = nil

    if params[:filterrific]
      $ssub = params[:filterrific][:with_subcategory_id]
    end
puts "SSUB JE #{$ssub}"
    # filterific ###########################################################################################################################
    @page_title = "Artikli"
    @filterrific = initialize_filterrific(Article.where(raw: true, for_sale: true ), params[:filterrific], select_options: { sorted_by: Article.options_for_sorted_by,
                                                                                                                                                              with_subcategory_id: Subcategory.options_for_select,
                                                                                                                                                              with_ssubcategory_id: Ssubcategory.options_for_select,
                                                                                                                                                              with_color_id: Color.options_for_select,
                                                                                                                                                              with_type_id: Type.options_for_select},:persistence_id => false,) or return


    @articles = @filterrific.find.page(params[:page])

    respond_to do |format|
      format.html
      format.js
    end


  rescue ActiveRecord::RecordNotFound => e
    # There is an issue with the persisted param_set. Reset it.
    puts "Had to reset filterrific params: #{ e.message }"
    redirect_to(reset_filterrific_url(format: :html)) and return

    ###########################################################################################################################

  end

  def show
    @article = Article.find_by(id: params[:format], for_sale: true)

    if @article != nil
      rel_art_ids = []
      @rel_arts = []

      rel_art_ids = RelatedArticle.where(article_id: @article.id).pluck(:related_article_id)

      @rel_arts = Article.where(id: rel_art_ids)

      if current_user != nil
        @shopping_cart = ShoppingCart.find_by(user_id: current_user.id)

        puts "Shopping cart ID: #{@shopping_cart.id}"

        @carts_article = CartsArticle.find_by(shopping_cart_id: @shopping_cart.id )
      else
        puts "NEMA USER-A!!!!"
          @articles = Article.where(id: $no_user_articles.keys)
          @sa = SingleArticle.where(id: $no_user_single_articles.keys)

      end
    else
      flash[:error] = "Taj artikl ne postoji!"
      redirect_to :back
    end

  end
end

app/helpers/repromaterijal_helper.rb
module RepromaterijalHelper
end

app/views/repromaterijal/_cat_pics.erb
<div id="filterrific_results">

  <div class="about">
    <div class="container">
      <div class="about-top grid-1">
        <% subcategories.each do |subcategory| %>
            <div class="col-md-4 about-left">
              <%= link_to index_of_repromaterijal_index_path(id: subcategory.id), :method => :get do %>
                  <figure class="effect-bubba shadow">
                    <% if subcategory.avatar_file_name.nil? %>
                      <%=image_tag("slika_kateg.jpg", class: "img-responsive" ) %>
                    <% else %>
                      <%=image_tag(subcategory.avatar.url(:index), class: "img-responsive" ) %>
                    <% end %>
                    <!--TODO: upisati naziv kategorije-->
                    <figcaption>
                      <h2><%= subcategory.title %></h2>
                      <p>Kratki opis kategorije</p>
                    </figcaption>
                  </figure>
              <% end %>
            </div>
        <% end %>
        <div class="clearfix"></div>
      </div>
    </div>
  </div>

</div>

<%= paginate subcategories %>

app/views/repromaterijal/_show_pics.html.erb
<div id="filterrific_results">



  <% articles.each do |art| %>

      <div class="product-one col-md-4 product-left ">
        <% if art.on_discount == true && art.end_date != nil %>
            <div class="timer_popust" >
              <h5><div data-countdown="<%= art.end_date.strftime("%Y/%m/%d %H:%M") %>" style="color: white;"></div></h5>
            </div>
        <% end %>
        <div class="product-main simpleCart_shelfItem">

          <!--TODO: upisati naziv slike-->

          <% if art.picture != nil %>
                <%=link_to  repromaterijal_show_path(art.id)  do %> <%= image_tag(art.picture.image.url(:index), class: "img-responsive zoom-img" ) %> <% end %>
          <% else %>
                <%=link_to  repromaterijal_show_path(art.id)  do %> <%= image_tag("placeholder_index.png", class: "img-responsive zoom-img" ) %> <% end %>
          <% end %>
          <div class="product-bottom">
            <h3><%= art.title %></h3>
            <!--NOTE: kratki opis od jednog reda-->

            <% if art.short_description != nil && art.short_description !=""  %>
                <h4><%= art.short_description  %></h4>
            <% else %>
                <h4>-</h4>
            <% end %>

            <% if art.on_discount == true && art.discount != 0 %>
                <h4><%= link_to carts_articles_create_path(art.id ), class: "item_add"  do %><i></i><% end %><span class=" item_price"><%= number_to_currency(art.cost-(art.cost*art.discount/100), :unit => 'Kn', :format => "%n %u") %></span></h4>
            <% else %>
                <h4><%= link_to carts_articles_create_path(art.id ), class: "item_add"  do %><i></i><% end %><span class=" item_price"><%= number_to_currency(art.cost, :unit => 'Kn', :format => "%n %u") %></span></h4>
            <% end %>
          </div>
          <% if art.on_discount == true && art.discount != 0 %>
              <div class="srch">
                <span><%= art.discount %>%</span>
              </div>
          <% end %>
        </div>
      </div>
  <% end %>



  <div class="row">
    <div class="col-md-12">
      <%= paginate articles %>
    </div>
  </div>

</div>

app/views/repromaterijal/categories.erb
        <%= render(
                partial: 'repromaterijal/cat_pics',
                locals: { subcategories: @subcategories }
            ) %>

app/views/repromaterijal/categories.js.erb
<% js = escape_javascript(
  render(partial: 'repromaterijal/cat_pics', locals: { subcategories: @subcategories })
) %>
$("#filterrific_results").html("<%= js %>");

app/views/repromaterijal/index.html.erb
<div class="bnr" id="home">
  <div id="top" class="callbacks_container">
    <ul class="rslides" id="slider4">
      <% ShopBanner.where(active: true).each do |bann| %>
          <li>
            <%=image_tag(bann.image.url(:bannsm)) %>
          </li>
      <% end %>
    </ul>
  </div>
  <div class="clearfix"> </div>
</div>
<!--bottom-header-->
<!--start-breadcrumbs-->

<!--end-breadcrumbs-->
<!--prdt-starts-->
<%= form_for_filterrific @filterrific do |f| %>
    <div class="prdt">
      <div class="container">
        <div class="prdt-top">
          <div class="col-md-9 prdt-left">
            <%= render_filterrific_spinner %>
            <%= render(
                    partial: 'repromaterijal/show_pics',
                    locals: { articles: @articles }
                ) %>

          </div>

          <%# give the search field the 'filterrific-periodically-observed' class for live updates %>


          <div class="col-md-3 prdt-right">
            <div class="w_sidebar">

              <section class="sky-form">
                <h4>Pretraga</h4>
                <div class="row1 scroll-pane">

                  <div class="col col-4">
                    <%= f.text_field(
                            :search_query,
                            class: 'form-control filterrific-periodically-observed', placeholder: "pretraga proizvoda..."
                        ) %>

                  </div>
                </div>
              </section>

              <section class="sky-form">
                <h4>Sortiraj po</h4>
                <div class="row1 scroll-pane">

                  <div class="col col-4">
                    <%= f.select(
                            :sorted_by,
                            @filterrific.select_options[:sorted_by],
                            { include_blank: false }, class: 'form-control'
                        )%>

                  </div>
                </div>
              </section>


              <section class="sky-form">
                <h4>Kategorije</h4>
                <div class="row1 scroll-pane" style=" padding-top: 10px; padding-bottom: 35px;">

                  <div class="col col-4" style="float: right; position: absolute; display: block;">
                    <%= f.collection_select(
                           :with_subcategory_id,
                           Subcategory.order(:title),
                           :id,
                           :title,
                           { include_blank: '- Sve -' },
                           class: 'filterrific-periodically-observed chosen-select'
                       ) %>
                  </div>
                </div>
              </section>

              <section class="sky-form">
                <h4>PodKategorije</h4>
                <div class="row1 scroll-pane"  style=" padding-top: 10px; padding-bottom: 35px;">

                  <div class="col col-4"  style="float: right; position: absolute; display: block;">
                    <%= f.grouped_collection_select(
                           :with_ssubcategory_id,
                           Subcategory.order(:title),
                           :ssubcategories,
                           :title,
                           :id,
                           :title,
                           {:include_blank => true },
                           :as => :hidden,
                           :class=>'chosen-select',
                           style: 'height: auto;'
                       ) %>
                  </div>
                </div>
              </section>

              <%# give the search field the 'filterrific-periodically-observed' class for live updates %>

              <section class="sky-form">
                <h4>CIJENA</h4>
                <div>
                  <%= f.text_field(
                          :min_cost,
                          class: 'form-control filterrific-periodically-observed', id: 'range', multiple: true
                      ) %>

                </div>
              </section>

            </div>
          </div>
<% end %>
<div class="clearfix"></div>

</div>
</div>
</div><!--product-end-->
<!--kraj sidebara -->
<!--product-end-->


<script>

  $('[data-countdown]').each(function() {
    var $this = $(this), finalDate = $(this).data('countdown');
    $this.countdown(finalDate, function(event) {
      $this.html(event.strftime('%D dana %H:%M:%S'));
    });
  })
</script>

<script>
  $(function () {

    $("#range").ionRangeSlider({
      hide_min_max: true,
      keyboard: true,
      min: parseFloat(gon.min).toFixed(2),
      max: parseFloat(gon.max).toFixed(2),
      from_max: gon.max-1,
      to_min: gon.min+1,
      from: 0,
      to: 5000,
      type: 'double',
      step: 1,
      postfix: " kn",
      grid: true
    });

  });

</script>

app/views/repromaterijal/index.js.erb
<% js = escape_javascript(
  render(partial: 'repromaterijal/show_pics', locals: { articles: @articles })
) %>
$("#filterrific_results").html("<%= js %>");

$('[data-countdown]').each(function () {
  var $this = $(this), finalDate = $(this).data('countdown');
  $this.countdown(finalDate, function (event) {
    $this.html(event.strftime('%D dana %H:%M:%S'));
  });
});

jQuery(function() {
  var categories, material, options;
  categories = $('#filterrific_with_ssubcategory_id').html();
  material = $('#filterrific_with_subcategory_id :selected').text();

  if (material === "- Sve -") {
    $('#filterrific_with_ssubcategory_id').empty();
    $('#filterrific_with_ssubcategory_id').trigger("chosen:updated");

  } else {
    options = $(categories).filter("optgroup[label='" + material + "']").html();
    $('#filterrific_with_ssubcategory_id').html(options);
    $('#filterrific_with_ssubcategory_id').trigger("chosen:updated");

  }


});

app/views/repromaterijal/index_of.js.erb
/**
 * Created by Stroj on 15.2.2016..
 */
<% js = escape_javascript(
  render(partial: 'trgovina/show_pics', locals: { articles: @articles })
) %>
$("#filterrific_results").html("<%= js %>");

$('[data-countdown]').each(function () {
  var $this = $(this), finalDate = $(this).data('countdown');
  $this.countdown(finalDate, function (event) {
    $this.html(event.strftime('%D dana %H:%M:%S'));
  });
});

app/views/repromaterijal/show.html.erb
<!--start-breadcrumbs-->
<div class="breadcrumbs">
  <div class="container">
    <div class="breadcrumbs-main">
      <ol class="breadcrumb">
        <%= render_breadcrumbs :separator => '/' %>
        <!--TODO: staviti naziv artikla koji je na stranici-->
        <li class="active">/<%= @article.title %></li>
      </ol>
    </div>
  </div>
</div>
<!--end-breadcrumbs-->

<!--start-single-->

<div class="single contact">
  <div class="container">
    <div class="single-main">
      <div class="col-md-12 single-main-left">
        <div class="sngl-top">
          <div class="col-md-4 single-top-left">

            <% if @article.on_discount == true && @article.discount != 0 %>
                <div class="dialog-srch srch">
                  <span><%= @article.discount %>%</span>
                </div>
            <% end %>
            <!--TODO: postotak na modal dialogu-->
            <div class="item">
              <div class="clearfix" style="max-width:474px;">
                <ul id="image-gallery" class="thumbnail gallery list-unstyled cS-hidden">
                  <% if !@article.pictures.first.nil? %>
                      <% @ind = @article.picture.image.url(:picture) %>
                      <li   data-thumb="<%=  @article.picture.image.url(:thumbgal) %>">
                        <%= image_tag(@article.picture.image.url(:picture)) %>
                      </li>
                      <% @article.pictures.each do |pic| %>

                          <% if @ind != pic.image.url(:picture) %>

                              <li data-thumb="<%=  pic.image.url(:thumbgal) %>">
                                <%= image_tag(pic.image.url(:picture)) %>
                              </li>

                          <% end %>
                      <% end %>
                  <% end %>

                </ul>
              </div>
            </div>


          </div>
          <div class="col-md-7 details">

            <div class="product-bottom">
              <div class="productboxkat"><%= @article.subcategory.title %></div>
              <div class="row naslov-site">
                <% if @article.on_discount %>
                  <div class="productboxkat"><strong><div data-countdown="<%= @article.end_date.strftime("%Y/%m/%d %H:%M") %>"></div></strong></div>
                <% end %>
                    <div class="productbox"><%= @article.title %></div>

                <% if @article.on_discount == true && @article.discount != 0 %>
                    <div class="productboxprice" style="margin-left: 10px;"><span class=" item_price"><%= number_to_currency(@article.cost-(@article.cost*@article.discount/100), :unit => 'Kn', :format => "%n %u") %></span></div>
                    <div class="productboxprice"><span class=" item_price" style="text-decoration: line-through;"><%= number_to_currency(@article.cost, :unit => 'Kn', :format => "%n %u") %></span></div>
                <% else %>
                    <div class="productboxprice"><span class=" item_price"><%= number_to_currency(@article.cost, :unit => 'Kn', :format => "%n %u") %></span></div>
                <% end %>
              </div>
              <div class="row">
                <div class="productboxkata"><strong>Kod Artikla:</strong> <%= @article.code %></div>
              </div>
              <div class="productboxopis-site">
                <p><%= @article.description %></p>
              </div>
              <div class="productboxopis-site">
                <% if !@article.weight.nil? %>
                    <p><strong>Težina:</strong> <%= @article.weight %>g </p>
                <% end %>

                <% if !@article.dimension.nil? %>
                    <p><strong>Dimenzije:</strong> <%= @article.dimension %></p>
                <% end %>
              </div>

              <%= simple_form_for @article, url:  @article.single_articles.first != nil ?  create_single_carts_articles_path : carts_articles_path, :method => :post, html: {class: ""} do |f| %>

                  <%= f.input :id, :as => :hidden %>

                  <div class="row" style="margin-bottom:20px;">



                    <div class="row" >

                      <% if @article.single_articles.first != nil %>
                          <% if @article.single_articles.first.size != "" && @article.single_articles.first.size != nil %>

                              <div class="col-md-6 artikli_margin_none">
                                <div class="productboxcolor">Veličina* </div>

                                <%= f.input :size, label: false, collection: SingleArticle.where(article_id: f.object.id).pluck(:size), class: "ddboje",:include_blank => false  %>

                              </div>
                          <% end %>
                      <% end %>


                    </div>

                    <div class="row" >

                      <div class="col-md-6 artikli_margin_none">
                        <div class="productboxcolor">Količina*</div>

                        <%= f.input :amount, label: false ,input_html: { value: 1} %>

                      </div>
                    </div>

                    <div class="row ">
                      <div class="col-md-6 artikli_margin_none">
                        <div class="hcart">
                          <h4><span><%= button_tag(type: 'submit', class: 'btn btn-default gumb_kupnja') do %> <i></i>Dodaj u košaricu <% end %></span></h4>
                        </div>
                      </div>

                    </div>
                    </div>


                    </div>
                    <div class="clearfix"> </div>
                    </div>
                    </div>
                    <div class="clearfix"> </div>
                    </div>
                    </div>


              <% end %>

              <% if  !@rel_arts.nil? && !@rel_arts.empty? %>
                  <div class="page-header" style="padding-left: 25px; margin: 0;">
                    <h1>Srodni Artikli</h1>
                  </div>

                  <div class="row" >
                    <div class="prdt-top">
                      <div class="col-md-12 prdt-left">
                        <% @rel_arts.each do |art| %>

                            <% if art.raw == true %>
                                <div class="product-one col-md-3 product-left ">
                                  <div class="product-main simpleCart_shelfItem">
                                    <!--TODO: upisati naziv slike-->

                                    <% if art.picture != nil %>
                                        <%=link_to  repromaterijal_show_path(art.id)  do %> <%= image_tag(art.picture.image.url(:index), class: "img-responsive zoom-img" ) %> <% end %>
                                    <% else %>
                                        <%=link_to  repromaterijal_show_path(art.id)  do %> <%= image_tag("placeholder_index.png", class: "img-responsive zoom-img" ) %> <% end %>
                                    <% end %>
                                    <div class="product-bottom">
                                      <h3><%= art.title %></h3>
                                      <!--NOTE: kratki opis od jednog reda-->
                                      <p>detalji</p>

                                      <h4><%= link_to carts_articles_create_path(art.id ), class: "item_add"  do %><i></i><% end %><span class=" item_price"><%= number_to_currency(art.cost, :unit => 'Kn', :format => "%n %u") %></span></h4>

                                    </div>
                                    <% if art.on_discount == true && art.discount != 0 %>
                                        <div class="srch">
                                          <span><%= art.discount %>%</span>
                                        </div>
                                    <% end %>
                                  </div>
                                </div>
                            <% else %>
                                <div class="product-one col-md-3 product-left ">
                                  <div class="product-main simpleCart_shelfItem">
                                    <!--TODO: upisati naziv slike-->
                                    <%=link_to  trgovina_show_path(art.id)  do %> <% if !art.picture.nil? %> <%= image_tag(art.picture.image.url(:index), class: "img-responsive zoom-img") %><% else %> <%= image_tag('placeholder_index.png', class: "img-responsive zoom-img") %> <% end %> <% end %>
                                    <div class="product-bottom">
                                      <h3><%= art.title %></h3>
                                      <!--NOTE: kratki opis od jednog reda-->
                                      <p>detalji</p>

                                      <h4><%= link_to carts_articles_create_path(art.id ), class: "item_add"  do %><i></i><% end %><span class=" item_price"><%= number_to_currency(art.cost, :unit => 'Kn', :format => "%n %u") %></span></h4>

                                    </div>
                                    <% if art.on_discount == true && art.discount != 0 %>
                                        <div class="srch">
                                          <span><%= art.discount %>%</span>
                                        </div>
                                    <% end %>
                                  </div>
                                </div>
                            <% end %>

                            <%# give the search field the 'filterrific-periodically-observed' class for live updates %>

                        <% end %>
              <% end %>
              </div>
              <div class="clearfix"></div>
              </div>
              </div>
              </div>
</div>
              <!--end-single-->

<script>
  $('[data-countdown]').each(function () {
    var $this = $(this), finalDate = $(this).data('countdown');
    $this.countdown(finalDate, function (event) {
      $this.html(event.strftime('%D dana %H:%M:%S'));
    });
  });
</script>